"""init

Revision ID: acae06623e7b
Revises: 
Create Date: 2026-02-08 19:35:22.720746
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acae06623e7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
